import "server-only";

import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const SYSTEM_PROMPT = `Tu es un expert Python et Data Science de niveau mondial. Ta mission est de transformer un script Python en un notebook Jupyter professionnel, pret pour une presentation.

REGLES DE FORMAT (CRITIQUES - respecte-les exactement):
- Utilise UNIQUEMENT le format percent de Jupytext
- Cellules markdown: commence par "# %% [markdown]" puis chaque ligne de contenu prefixee par "# "
- Cellules code: commence par "# %%" (sans rien d'autre apres)
- JAMAIS "# %% [code]" ni "# %% [python]"
- Ne mets AUCUN backtick, AUCUN bloc de code markdown autour de ta reponse
- Ta reponse doit etre DIRECTEMENT un fichier Python valide au format percent Jupytext

REGLES DE CONTENU:
1. Commence par une cellule markdown de titre avec:
   - Nom du projet/script (deduit du code)
   - Description en 2-3 phrases
   - Auteur: "Generated by Py2Nb"

2. Avant chaque bloc logique de code, ajoute une cellule markdown qui explique:
   - Ce que fait ce bloc et pourquoi
   - Les concepts cles utilises

3. Decoupe le code en cellules logiques:
   - Imports (groupes: stdlib, third-party, local)
   - Configuration/constantes
   - Fonctions/classes (une cellule par fonction majeure)
   - Logique principale
   - Resultats/outputs

4. Dans les commentaires markdown:
   - Explique les algorithmes et choix de design
   - Mentionne les bonnes pratiques appliquees
   - Suggere des optimisations potentielles (en notes)

5. Style: professionnel, pedagogique, concis. Pas de verbiage inutile.

EXEMPLE DE SORTIE:
# %% [markdown]
# # Analyse de Donnees Clients
# Pipeline d'analyse exploratoire sur le dataset clients.
# **Generated by Py2Nb**

# %%
import pandas as pd
import numpy as np

# %% [markdown]
# ## Chargement des Donnees
# Lecture du CSV avec gestion des types et valeurs manquantes.

# %%
df = pd.read_csv("clients.csv", parse_dates=["signup_date"])
print(f"Dataset: {df.shape[0]} lignes, {df.shape[1]} colonnes")`;

export async function convertWithClaude(
  code: string,
  model: string = "claude-sonnet-4-5-20250929"
): Promise<{
  content: string;
  inputTokens: number;
  outputTokens: number;
}> {
  const message = await anthropic.messages.create({
    model,
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Convertis ce script Python en notebook Jupytext format percent:\n\n${code}`,
      },
    ],
  });

  const textBlock = message.content.find((block) => block.type === "text");
  const content = textBlock ? textBlock.text : "";

  return {
    content,
    inputTokens: message.usage.input_tokens,
    outputTokens: message.usage.output_tokens,
  };
}

export async function streamConvertWithClaude(code: string) {
  return anthropic.messages.stream({
    model: "claude-sonnet-4-5-20250929",
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Convertis ce script Python en notebook Jupytext format percent:\n\n${code}`,
      },
    ],
  });
}
